version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install BOOST for testing and other stuff
          command: 'apt-get update && apt-get install -y libboost-all-dev'
      - run:
          name: Install MAKE and CMAKE
          command: 'apt-get update && sudo apt-get install -y make cmake'
      - run:
          name: Install doxygen
          command: 'apt-get update && sudo apt-get install -y doxygen'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Unit Testing
          command: 'cd build && ctest'
